[project]
name = "cherry-etl"
version = "0.9.0"
description = "Library for building blockchain pipelines"
repository = "https://github.com/steelcake/cherry"
homepage = "https://github.com/steelcake/cherry"
readme = "README.md"
license = "MIT OR Apache-2.0"
authors = [
  { name = "Ozgur Akkurt", email = "ozgur@steelcake.com" },
  { name = "Yule Andrade", email = "yule@steelcake.com" },
]
requires-python = ">=3.11"
dependencies = [
    "cherry-core",
    "pyarrow>=22.0.0",
    "sqlalchemy>=2.0.38",
    "psycopg2-binary>=2.9.0",
    "pyiceberg>=0.10.0",
    "clickhouse-connect>=0.9.2",
    "deltalake>=1.2.1",
    "polars>=1.34.0",
    "duckdb>=1.4.1",
    "datafusion>=50.1.0",
]

[dependency-groups]
dev = [
    "dotenv>=0.9.9",
    "pytest>=8.3.5",
    "ruff>=0.9.7",
    "base58>=2.1.1",
    "pyright>=1.1.400",
]

[tool.uv.sources]
cherry-core = { path = "../cherry-core/python", editable = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

